# 应用服务 WEB 访问端口
server.port: 8081

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_word?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    # type: com.alibaba.druid.pool.DruidDataSource # 配置连接池

  # MyBatis 核心配置
mybatis:
  # 1.配置Mapper XML文件扫描路径
  # 若你用默认路径（接口与XML同包），可替换为：
  mapper-locations: classpath:mapper/*.xml
  # 2. 实体类别名扫描（简化XML配置）
  type-aliases-package: com.sinosoft.wordweb.chat.domain.entity
  # 3. 自定义MyBatis运行时配置
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出SQL（开发环境必备）
#      default-fetch-size: 100 # 默认查询结果集大小（可选）
#      default-statement-timeout: 30 # 默认SQL执行超时时间（可选，单位：秒）

  ## Redis服务连接配置
  #spring:
  #  redis:
  #    host: 127.0.0.1
  #    port: 6379
  #    password: sinosoft!@#admin
  #    timeout: 5000ms
  #    lettuce:
  #      pool:
  #        max-active: 8
  #        max-idle: 8
  #        min-idle: 2
  #      shutdown-timeout: 1000ms
